/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package handson5;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class panelDataSupplier extends javax.swing.JPanel {

    Connection conn = Handson5.getKoneksi();
    DefaultTableModel model;
    public panelDataSupplier() {
        initComponents();
        isiBarangDipasok();
        tampilData();
        bersih();
    }
    private void isiBarangDipasok() {
        cmbBarangDipasok.removeAllItems();
        cmbBarangDipasok.addItem("-- Pilih Barang Dipasok --");

        try {
            String sql = "SELECT DISTINCT kategori_barang FROM barang";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                cmbBarangDipasok.addItem(rs.getString("kategori_barang"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat barang dipasok: " + e.getMessage());
        }
    }
    private void tampilData() {
        model = new DefaultTableModel();
        model.addColumn("Kode Supplier");
        model.addColumn("Nama Supplier");
        model.addColumn("Barang Dipasok");
        model.addColumn("Nama Kontak");
        model.addColumn("No Handphone");
        model.addColumn("Alamat");

        tblSupplier.setModel(model);

        try {
            String sql = "SELECT * FROM supplier ORDER BY kode_supplier ASC";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("kode_supplier"),
                    rs.getString("nama_supplier"),
                    rs.getString("barang_dipasok"),
                    rs.getString("nama_kontak_supplier"),
                    rs.getString("no_handphone"),
                    rs.getString("alamat")
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal menampilkan data supplier: " + e.getMessage());
        }
    }
    private void bersih() {
        txtKodeSupplier.setText("");
        txtNamaSupplier.setText("");
        txtNamaKontak.setText("");
        txtNoHandphone.setText("");
        txtAlamat.setText("");

        if (cmbBarangDipasok.getItemCount() > 0) {
            cmbBarangDipasok.setSelectedIndex(0);
        }

        txtKodeSupplier.requestFocus();
    }
    private boolean validasiInput() {
        if (txtKodeSupplier.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Kode supplier harus diisi!");
            txtKodeSupplier.requestFocus();
            return false;
        }

        if (txtNamaSupplier.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nama supplier harus diisi!");
            txtNamaSupplier.requestFocus();
            return false;
        }

        if (cmbBarangDipasok.getSelectedItem() == null || cmbBarangDipasok.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Barang dipasok harus dipilih!");
            cmbBarangDipasok.requestFocus();
            return false;
        }

        if (txtNamaKontak.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nama kontak supplier harus diisi!");
            txtNamaKontak.requestFocus();
            return false;
        }

        if (txtNoHandphone.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "No. handphone harus diisi!");
            txtNoHandphone.requestFocus();
            return false;
        }

        if (txtAlamat.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Alamat harus diisi!");
            txtAlamat.requestFocus();
            return false;
        }

        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtKodeSupplier = new javax.swing.JTextField();
        txtNamaSupplier = new javax.swing.JTextField();
        txtNamaKontak = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNoHandphone = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cmbBarangDipasok = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAlamat = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblSupplier = new javax.swing.JTable();
        txtSimpan = new javax.swing.JButton();
        txtSimpan1 = new javax.swing.JButton();
        txtSimpan2 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setBackground(new java.awt.Color(255, 250, 240));
        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Data Supplier", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 18))); // NOI18N

        jLabel1.setText("Kode Supplier");

        jLabel5.setText("Nama Kontak Supplier");

        jLabel4.setText("No. Handphone");

        jLabel3.setText("Barang Dipasok");

        cmbBarangDipasok.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbBarangDipasok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBarangDipasokActionPerformed(evt);
            }
        });

        jLabel2.setText("Nama Supplier");

        jLabel6.setText("Alamat");

        txtAlamat.setColumns(20);
        txtAlamat.setRows(5);
        jScrollPane1.setViewportView(txtAlamat);

        tblSupplier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblSupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSupplierMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblSupplier);

        txtSimpan.setBackground(new java.awt.Color(129, 145, 47));
        txtSimpan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtSimpan.setForeground(new java.awt.Color(248, 196, 99));
        txtSimpan.setText("SIMPAN");
        txtSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSimpanActionPerformed(evt);
            }
        });

        txtSimpan1.setBackground(new java.awt.Color(129, 145, 47));
        txtSimpan1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtSimpan1.setForeground(new java.awt.Color(248, 196, 99));
        txtSimpan1.setText("EDIT");
        txtSimpan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSimpan1ActionPerformed(evt);
            }
        });

        txtSimpan2.setBackground(new java.awt.Color(129, 145, 47));
        txtSimpan2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtSimpan2.setForeground(new java.awt.Color(248, 196, 99));
        txtSimpan2.setText("HAPUS");
        txtSimpan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSimpan2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtKodeSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNamaKontak, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNamaSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNoHandphone, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(39, 39, 39))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(txtSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtSimpan1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtSimpan2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbBarangDipasok, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(98, 98, 98))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtKodeSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtNamaSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cmbBarangDipasok, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtNoHandphone)
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSimpan1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSimpan2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNamaKontak, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtSimpan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSimpan1ActionPerformed
        if (txtKodeSupplier.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Pilih data supplier yang ingin diedit!");
            return;
        }

        if (!validasiInput()) {
            return;
        }

        try {
            String sql = "UPDATE supplier SET "
                    + "nama_supplier = ?, "
                    + "barang_dipasok = ?, "
                    + "nama_kontak_supplier = ?, "
                    + "no_handphone = ?, "
                    + "alamat = ? "
                    + "WHERE kode_supplier = ?";

            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, txtNamaSupplier.getText());
            pst.setString(2, cmbBarangDipasok.getSelectedItem().toString());
            pst.setString(3, txtNamaKontak.getText());
            pst.setString(4, txtNoHandphone.getText());
            pst.setString(5, txtAlamat.getText());
            pst.setString(6, txtKodeSupplier.getText());

            pst.executeUpdate();

            JOptionPane.showMessageDialog(this, "Data supplier berhasil diedit!");
            tampilData();
            bersih();
            txtKodeSupplier.setEnabled(true);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal mengedit data supplier: " + e.getMessage());
        }
    }//GEN-LAST:event_txtSimpan1ActionPerformed

    private void txtSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSimpanActionPerformed
        if (!validasiInput()) {
            return;
        }

        try {
            String sql = "INSERT INTO supplier "
                    + "(kode_supplier, nama_supplier, barang_dipasok, nama_kontak_supplier, no_handphone, alamat) "
                    + "VALUES (?, ?, ?, ?, ?, ?)";

            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, txtKodeSupplier.getText());
            pst.setString(2, txtNamaSupplier.getText());
            pst.setString(3, cmbBarangDipasok.getSelectedItem().toString());
            pst.setString(4, txtNamaKontak.getText());
            pst.setString(5, txtNoHandphone.getText());
            pst.setString(6, txtAlamat.getText());

            pst.executeUpdate();

            JOptionPane.showMessageDialog(this, "Data supplier berhasil disimpan!");
            tampilData();
            bersih();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal menyimpan data supplier: " + e.getMessage());
        }
    }//GEN-LAST:event_txtSimpanActionPerformed

    private void tblSupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSupplierMouseClicked
        int baris = tblSupplier.getSelectedRow();

        if (baris != -1) {
            txtKodeSupplier.setText(tblSupplier.getValueAt(baris, 0).toString());
            txtNamaSupplier.setText(tblSupplier.getValueAt(baris, 1).toString());
            cmbBarangDipasok.setSelectedItem(tblSupplier.getValueAt(baris, 2).toString());
            txtNamaKontak.setText(tblSupplier.getValueAt(baris, 3).toString());
            txtNoHandphone.setText(tblSupplier.getValueAt(baris, 4).toString());
            txtAlamat.setText(tblSupplier.getValueAt(baris, 5).toString());

            txtKodeSupplier.setEnabled(false);
        }
    }//GEN-LAST:event_tblSupplierMouseClicked

    private void txtSimpan2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSimpan2ActionPerformed

        if (txtKodeSupplier.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Pilih data supplier yang ingin dihapus!");
            return;
        }

        int konfirmasi = JOptionPane.showConfirmDialog(
                this,
                "Apakah Anda yakin ingin menghapus data supplier ini?",
                "Konfirmasi Hapus",
                JOptionPane.YES_NO_OPTION
        );

        if (konfirmasi == JOptionPane.YES_OPTION) {
            try {
                String sql = "DELETE FROM supplier WHERE kode_supplier = ?";
                PreparedStatement pst = conn.prepareStatement(sql);
                pst.setString(1, txtKodeSupplier.getText());
                pst.executeUpdate();

                JOptionPane.showMessageDialog(this, "Data supplier berhasil dihapus!");
                tampilData();
                bersih();
                txtKodeSupplier.setEnabled(true);

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Gagal menghapus data supplier: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_txtSimpan2ActionPerformed

    private void cmbBarangDipasokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBarangDipasokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbBarangDipasokActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbBarangDipasok;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tblSupplier;
    private javax.swing.JTextArea txtAlamat;
    private javax.swing.JTextField txtKodeSupplier;
    private javax.swing.JTextField txtNamaKontak;
    private javax.swing.JTextField txtNamaSupplier;
    private javax.swing.JTextField txtNoHandphone;
    private javax.swing.JButton txtSimpan;
    private javax.swing.JButton txtSimpan1;
    private javax.swing.JButton txtSimpan2;
    // End of variables declaration//GEN-END:variables
}
